import deserek
import javaConst
obj = deserek.serListOfObj(value=[
  deserek.serTC_OBJECT(
    classDesc=deserek.serTC_CLASSDESC(
      className=deserek.serJavaString(
        value="java.util.HashMap",
        ),
      UID=deserek.serUID(
        value=362498820763181265,
        ),
      handle=deserek.serHandle(
        value=8257536,
        ),
      classDescFlags=deserek.serClassFlags(value=0|javaConst.SC_WRITE_METHOD|javaConst.SC_SERIALIZABLE),
      fields=deserek.serListOfObj(value=[
        deserek.serPrimitiveDesc(
          typecode=70,
          fieldName=deserek.serJavaString(
            value="loadFactor",
            ),
          ),
        deserek.serPrimitiveDesc(
          typecode=73,
          fieldName=deserek.serJavaString(
            value="threshold",
            ),
          )
        ]),
      classAnnotation=deserek.serListOfObj(value=[
        deserek.serTC_ENDBLOCKDATA()
        ]),
      superClassDesc=deserek.serTC_NULL(),
      ),
    handle=deserek.serHandle(
      value=8257537,
      ),
    classData=deserek.serListOfObj(value=[
      deserek.serClassDescValues(
        _class_name="java.util.HashMap",
        serialdata=deserek.serListOfObj(value=[
          deserek.serValuePrimitive(
            _typecode_hint=70,
            value=0.75,
            ),
          deserek.serValuePrimitive(
            _typecode_hint=73,
            value=12,
            )
          ]),
        objectAnnotation=deserek.serListOfObj(value=[
          deserek.serTC_BLOCKDATA(
            size=8,
            value=b'\x00\x00\x00\x10\x00\x00\x00\x01',
            ),
          deserek.serTC_OBJECT(
            classDesc=deserek.serTC_CLASSDESC(
              className=deserek.serJavaString(
                value="java.net.URL",
                ),
              UID=deserek.serUID(
                value=-7627629688361524110,
                ),
              handle=deserek.serHandle(
                value=8257538,
                ),
              classDescFlags=deserek.serClassFlags(value=0|javaConst.SC_WRITE_METHOD|javaConst.SC_SERIALIZABLE),
              fields=deserek.serListOfObj(value=[
                deserek.serPrimitiveDesc(
                  typecode=73,
                  fieldName=deserek.serJavaString(
                    value="hashCode",
                    ),
                  ),
                deserek.serPrimitiveDesc(
                  typecode=73,
                  fieldName=deserek.serJavaString(
                    value="port",
                    ),
                  ),
                deserek.serObjectDesc(
                  typecode=76,
                  fieldName=deserek.serJavaString(
                    value="authority",
                    ),
                  className1=deserek.serTC_STRING(
                    value=deserek.serJavaString(
                      value="Ljava/lang/String;",
                      ),
                    ),
                  ),
                deserek.serObjectDesc(
                  typecode=76,
                  fieldName=deserek.serJavaString(
                    value="file",
                    ),
                  className1=deserek.serTC_REFERENCE(
                    handle=8257539,
                    ),
                  ),
                deserek.serObjectDesc(
                  typecode=76,
                  fieldName=deserek.serJavaString(
                    value="host",
                    ),
                  className1=deserek.serTC_REFERENCE(
                    handle=8257539,
                    ),
                  ),
                deserek.serObjectDesc(
                  typecode=76,
                  fieldName=deserek.serJavaString(
                    value="protocol",
                    ),
                  className1=deserek.serTC_REFERENCE(
                    handle=8257539,
                    ),
                  ),
                deserek.serObjectDesc(
                  typecode=76,
                  fieldName=deserek.serJavaString(
                    value="ref",
                    ),
                  className1=deserek.serTC_REFERENCE(
                    handle=8257539,
                    ),
                  )
                ]),
              classAnnotation=deserek.serListOfObj(value=[
                deserek.serTC_ENDBLOCKDATA()
                ]),
              superClassDesc=deserek.serTC_NULL(),
              ),
            handle=deserek.serHandle(
              value=8257540,
              ),
            classData=deserek.serListOfObj(value=[
              deserek.serClassDescValues(
                _class_name="java.net.URL",
                serialdata=deserek.serListOfObj(value=[
                  deserek.serValuePrimitive(
                    _typecode_hint=73,
                    value=-1,
                    ),
                  deserek.serValuePrimitive(
                    _typecode_hint=73,
                    value=-1,
                    ),
                  deserek.serTC_STRING(
                    value=deserek.serJavaString(
                      value="test.example.com",
                      ),
                    ),
                  deserek.serTC_STRING(
                    value=deserek.serJavaString(
                      value="/",
                      ),
                    ),
                  deserek.serTC_REFERENCE(
                    handle=8257541,
                    ),
                  deserek.serTC_STRING(
                    value=deserek.serJavaString(
                      value="http",
                      ),
                    ),
                  deserek.serTC_NULL()
                  ]),
                objectAnnotation=deserek.serListOfObj(value=[
                  deserek.serTC_ENDBLOCKDATA()
                  ]),
                )
              ]),
            ),
          deserek.serTC_STRING(
            value=deserek.serJavaString(
              value="http://test.example.com/",
              ),
            ),
          deserek.serTC_ENDBLOCKDATA()
          ]),
        )
      ]),
    )
  ])

open("test.bin",'wb').write(deserek.do_serialize(obj))